baseURL = "https://cube-blogrebuild.netlify.com"
languageCode = "en-us"
title = "CUBE blog"
disqusShortname = "cubemc"

[params]
description = "The JAMstack rebuild of the CUBEmc.com blog"
og_image = "images/cube-blog-under-construction.jpg"

[related]
threshold = 100
includeNewer = true
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 10


[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "linear"

# Default JPEG quality setting. Default is 75.
quality = 70

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"
