--- 
baseURL: "https://leactz.github.io/cubemc-blogrebuild/"
disqusShortname: cubemc
imaging: 
  anchor: smart
  quality: 70
  resampleFilter: linear
languageCode: en-us
params: 
  description: "The JAMstack rebuild of the CUBEmc.com blog"
  og_image: images/cube-blog-under-construction.jpg
related: 
  includeNewer: true
  indices: 
    - name: tags
      weight: 10
  threshold: 100
  toLower: false
title: "CUBE blog"